# Generated by Django 4.0.3 on 2022-03-23 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50)),
                ('mobilenum', models.IntegerField(unique=True)),
                ('email', models.EmailField(max_length=120)),
                ('password', models.CharField(max_length=50)),
            ],
        ),
    ]
