# Generated by Django 4.0.3 on 2022-03-24 04:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reg', '0002_postdetail_posthome_delete_userregistration'),
    ]

    operations = [
        migrations.RenameField(
            model_name='postdetail',
            old_name='user_image',
            new_name='post_image',
        ),
    ]
