# Generated by Django 4.0.3 on 2022-03-24 07:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reg', '0006_rename_msg_messagemodel_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='messagemodel',
            name='postuser',
        ),
    ]
