# Generated by Django 4.0.3 on 2022-03-24 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reg', '0007_remove_messagemodel_postuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='messagemodel',
            name='postid',
            field=models.IntegerField(null=True),
        ),
    ]
