# Generated by Django 4.0.3 on 2022-03-28 06:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reg', '0011_alter_followermodel_fweruserid_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PostHome',
        ),
    ]
