# Generated by Django 4.0.3 on 2022-03-28 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reg', '0013_postdetail_uploaded_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postdetail',
            name='post_image',
            field=models.FileField(null=True, upload_to=''),
        ),
    ]
